version: "3.3"

services:
  dind:
    image: "docker:dind"
    container_name: "jenkins-docker"
    privileged: true
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - "./jenkins/jenkins-docker-certs:/certs/client"
      - "./jenkins/jenkins-data:/var/jenkins_home"

  blueocean:
    image: jenkinsci/blueocean
    container_name: "jenkins-tutorial"
    networks:
      jenkins:
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - "./jenkins/jenkins-data:/var/jenkins_home"
      - "./jenkins/jenkins-docker-certs:/certs/client:ro"
    ports:
      - "8080:8080"
      - "50000:50000"

networks:
  jenkins: